# Generated by Django 6.1.1 on 2026-09-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_exam_studentexamscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='paper_set',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
