# Generated by Django 6.1.1 on 2026-09-29 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_personalnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mock_type', models.CharField(choices=[('quiz_30', 'Collegiate Quiz (30 Marks)'), ('pre_end_100', 'Pre-End Semester Exam (100 Marks)'), ('mcq_quiz', 'Interactive MCQ Mock Quiz')], default='quiz_30', max_length=30)),
                ('source_exam_title', models.CharField(blank=True, max_length=255)),
                ('total_marks', models.FloatField(default=30.0)),
                ('time_allowed_minutes', models.IntegerField(default=60)),
                ('difficulty', models.CharField(default='Standard', max_length=30)),
                ('instructions', models.JSONField(blank=True, default=list)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('questions_data', models.JSONField(blank=True, default=list)),
                ('model_used', models.CharField(default='gemini-1.5-flash', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_exams', to='api.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
