# Generated by Django 6.1.1 on 2026-09-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mockexam'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaperFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exam_type', models.CharField(max_length=100)),
                ('total_marks', models.IntegerField(default=30)),
                ('time_allowed_minutes', models.IntegerField(default=60)),
                ('has_sets', models.BooleanField(default=True)),
                ('paper_sets', models.JSONField(blank=True, default=list)),
                ('sections_data', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['total_marks', 'name'],
            },
        ),
    ]
